name: front_end
description: Cooper Casino's Frontend

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  carousel_slider: ^4.2.1
  onscreen_num_keyboard: ^1.0.4
  intl: ^0.19.0
  cupertino_icons: ^1.0.0
  http: ^1.2.1
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - lib/assets/images/login_logo.png
    - lib/assets/images/card-deck.png
    - lib/assets/images/roulette.png
    - lib/assets/images/slot-machine.png
    - lib/assets/images/red_curtains_left.png
    - lib/assets/images/red_curtains_right.png
    - lib/assets/sprites/slots-symbols/1xbar.png
    - lib/assets/sprites/slots-symbols/2xbar.png
    - lib/assets/sprites/slots-symbols/3xbar.png
    - lib/assets/sprites/slots-symbols/cherry.png
    - lib/assets/sprites/slots-symbols/clover.png
    - lib/assets/sprites/slots-symbols/lemon.png
    - lib/assets/sprites/slots-symbols/seven.png
    - lib/assets/sprites/slots-symbols/bell.png
    - lib/assets/sprites/slots-symbols/gem.png
    - lib/assets/sprites/slots-symbols/jackpot_style_2.png

  uses-material-design: true